#!/usr/bin/env php
<?php

use Spark\Application;
use Spark\Console\Kernel;

define('SPARK_START', microtime(true));

require __DIR__ . '/bootstrap/autoload.php';

$app = new Application(__DIR__);
$kernel = new Kernel($app);
exit($kernel->handle($argv));
